language: java
jdk:
  - openjdk8

before_install:
  - chmod +x gradlew
  
branches:
  only:
    - master
    
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r shoppingcart *
  - mkdir -p deploy
  - mv shoppingcart.zip deploy/shoppingcart.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: shoppingcart-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy
    wait-until-deployed: true
    on:
      repo: hkfoodis/shoppingcart #Github 주소
      branch: master    

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: shoppingcart-deploy
    key: shoppingcart.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: shoppingcart # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: shoppingcart-group # 웹 콘솔에서 등록한 CodeDeploy 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: hkfoodis/shoppingcart
      branch: master
      
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dlaehdud96@naver.com
  