spring:
  profiles:
    active: local #기본 환경 선택
    
---
spring: 
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 8082