spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: maple8542
    url: 'jdbc:mysql://localhost:3306/shopdb?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false     '
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
